### PR TITLE
Responsive CSS and favicon updated

### PR DESCRIPTION
**Pull request by si88har1h**
- I have done a universal reset for margins and padding. 
- Added responsive units to tackle different screen sizes. 
- Added a favicon to the page

Thanks for creating this repository. If you find my changes worth it please review them. Happy hacking!

### CODE REVIEW

**Comment by hctnm2** [comment]
Will Accept After Oct 1 because only then it will be valid

**Comment by si88har1h** [comment]
It started you can check on [Hacktoberfest](www.hacktoberfest.com) :)

**Comment by hctnm2** [comment]
image
Got the email a few minutes ago that said this

**Comment by si88har1h** [comment]
its Pacific Standard Time so in India its already started my other PR is up now :) But its alright thanks

**Pull request merged**
